spring.application.name=backend

spring.datasource.url=jdbc:postgresql://109.198.190.115:32322/ChevyirovaE
spring.datasource.username=student
spring.datasource.password=5432
spring.flyway.schemas= sporta, public
spring.flyway.baseline-on-migrate=true

jwt.secret=984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
jwt.lifetime=1h

